server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://192.168.42.42:9200
  rabbitmq:
    host: 192.168.42.42
    port: 5673
    virtual-host: /houshiyin
    username: houshiyin
    password: houshiyin
