server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.42.42:3306/guli_oms
    username: root
    password: 123456
  redis:
    host: 192.168.42.42
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/oms/**/*.xml
